site_name: HAIHA'S ELECTRIC
site_url: https://haihabk51.github.io/electric/

site_description: ELECTRIC
site_author: haihabk51

repo_url: https://github.com/haihabk51/electric/

theme:
  name: material
  icon:
    logo: fontawesome/solid/lightbulb-solid
    favicon: assets/meta/favicon.png
  font:
    text: Open Sans
    code: Roboto Mono
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: indigo
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode

features:
  - search.suggest
  - search.highlight
  - navigation.footer


plugins:
  - search
  - autolinks
  - callouts
  - blogging:
      dirs:
        - post
      template: overrides/custom-blog.html
      features:
        tags:
          index_page: tags.md
          insert: bottom
      time_format: ' %d-%m-%Y '


markdown_extensions:
  - wikilinks
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@nguyenhaihabk
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/hahtd3
    - icon: fontawesome/solid/bookmark
      link: https://substack.com/@nguyenhaiha
    - icon: fontawesome/solid/globe
      link: https://www.khoahocobsidian.com

copyright: Copyright &copy; 2024 haihanguyen
