site_name: OBSIDIAN VN
site_url: https://haihabk51.github.io/obsidianvietnam/

site_description: OBSIDIAN VN
site_author: haihabk51

repo_url: https://github.com/haihabk51/obsidianvietnam/

theme:
  name: material
  icon:
    logo: fontawesome/solid/lightbulb
    # favicon: assets/images/favicon.png  
    previous: fontawesome/solid/angle-left  # Thêm biểu tượng điều hướng "previous"
    next: fontawesome/solid/angle-right     # Thêm biểu tượng điều hướng "next"
  font:
    text: Open Sans
    code: Roboto Mono
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  

features:
  - search.suggest
  - search.highlight
  - navigation.footer
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.code.select

plugins:
  - obsidian-interactive-graph
  - search
  - callouts
  - embed_file
  - obsidian-bridge
  #- obsidian-support
  - glightbox
  - blogging:
      dirs:
        - post
      template: overrides/custom-blog.html
      features:
        tags:
          index_page: tags.md
          insert: bottom
      time_format: ' %d-%m-%Y '

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - md_in_html
  - def_list
  - sane_lists
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/obsidian_tags.css
  - assets/stylesheets/interactive_graph.css
  - assets/stylesheets/embed_link.css

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/interactive_graph.js
  - assets/javascripts/obsidian_tags.js

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@nguyenhaihabk
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/hahtd3
    - icon: fontawesome/solid/bookmark
      link: https://substack.com/@nguyenhaiha
    - icon: fontawesome/solid/globe
      link: https://www.khoahocobsidian.com

copyright: Copyright &copy; 2024 haihanguyen

nav:
  - Trang chủ: index.md
  - Giới thiệu: about.md
  - Obsidian cơ bản:
      - Bài 1: "Hướng dẫn xem bài và trả bài trên website và Facebook Group"
      - Bài 2: "Hướng dẫn cài đặt Obsidian trên Windows or Mac"
      - Bài 3: "Cách chia sẻ file nhanh với Obsidian_quickShare Plugin"
      - Bài 4: "Lấy file được chia sẻ hoặc lưu website về"
      - Bài 5: "Link Download Extension"
      - Bài 6: "Hướng dẫn làm việc giữa nhiều máy tính"
      - Bài 7: "Bắt đầu với những khái niệm ban đầu"
      - Bài 8: "Cách tạo một note theo ngày"
      - Bài 9: "Hướng dẫn dùng Canvas"
      - Bài 10: "Vẽ Mindmap trong Canvas (Cách 1)"
      - Bài 11: "Vẽ Mindmap trong Canvas (Cách 2)"
      - Bài 12: "Bài Tags và làm việc với tags"
      - Bài 13: "Các phương pháp tìm kiếm file"
      - Bài 14: "Hướng dẫn tìm kiếm file cơ bản"
      - Bài 15: "Hướng dẫn tìm kiếm file nâng cao"
      - Bài 16: "Chữa bài - Một số khó khăn"
      - Bài 17: "Một số Tip"
      - Bài 18: "Làm việc với các Workspace"