site_name: OBSIDIAN VN
site_url: https://haihabk51.github.io/obsidianvietnam/
site_description: OBSIDIAN VN
site_author: haihabk51
repo_url: https://github.com/haihabk51/obsidianvietnam/

theme:
  name: material
  icon:
    logo: fontawesome/solid/lightbulb
    # favicon: assets/images/favicon.png  
    previous: fontawesome/solid/angle-left  # Thêm biểu tượng điều hướng "previous"
    next: fontawesome/solid/angle-right     # Thêm biểu tượng điều hướng "next"
  font:
    text: Open Sans
    code: Roboto Mono
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

features:
  - search.suggest
  - search.highlight
  - navigation.footer
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.code.select

plugins:
  - obsidian-interactive-graph
  - search
  - callouts
  - embed_file
  - obsidian-bridge
  # - obsidian-support
  - glightbox
  - blogging:
      dirs:
        - post
      template: overrides/custom-blog.html
      features:
        tags:
          index_page: tags.md
          insert: bottom
      time_format: '%d-%m-%Y'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - md_in_html
  - def_list
  - sane_lists
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/obsidian_tags.css
  - assets/stylesheets/interactive_graph.css
  - assets/stylesheets/embed_link.css

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/interactive_graph.js
  - assets/javascripts/obsidian_tags.js

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@nguyenhaihabk
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/hahtd3
    - icon: fontawesome/solid/bookmark
      link: https://substack.com/@nguyenhaiha
    - icon: fontawesome/solid/globe
      link: https://www.khoahocobsidian.com

copyright: Copyright &copy; 2024 haihanguyen

nav:
  - Trang chủ: index.md
  - Giới thiệu: about.md
  - Obsidian cơ bản:
      - Bài 1 Hướng dẫn xem bài và trả bài trên website và Facebook Group: "https://www.youtube.com/watch?v=ULiLb4jYfgk"
      #- Bài 2: "Hướng dẫn cài đặt Obsidian trên Windows or Mac": "https://www.facebook.com/groups/219067851029823/posts/220012227602052/"
      #- Bài 3: "Cách chia sẻ file nhanh với Obsidian_quickShare Plugin": "https://www.youtube.com/watch?v=OG3ZutPNDb8&fbclid=IwAR2IDYg-EVx79Cc6QTPT0kgb3NQLztHdf_jVR6k_wXKvA6YmELjnnuLOIwk"
      #- Bài 4: "Lấy file được chia sẻ hoặc lưu website về": "https://www.youtube.com/watch?v=OG3ZutPNDb8"
      #- Bài 5: "Link Download Extension": "https://chrome.google.com/webstore/detail/markdownload-markdown-web/pcmpcfapbekmbjjkdalcgopdkipoggdi?fbclid=IwAR0NBRCwT2aJmHdVebu6AYvDEfLng_Scv3Fj3siKDdJwj9AvtM1IH6eKFn4"
      #- Bài 6: "Hướng dẫn làm việc giữa nhiều máy tính": "https://www.facebook.com/groups/219067851029823/posts/220015034268438/"
      