site_name: OBSIDIAN VN
site_url: https://haihabk51.github.io/obsidianvietnam/
site_description: OBSIDIAN VN
site_author: haihabk51
repo_url: https://github.com/haihabk51/obsidianvietnam/

theme:
  name: material
  icon:
    logo: fontawesome/solid/lightbulb
    # favicon: assets/images/favicon.png  
    previous: fontawesome/solid/angle-left  # Thêm biểu tượng điều hướng "previous"
    next: fontawesome/solid/angle-right     # Thêm biểu tượng điều hướng "next"
  font:
    text: Open Sans
    code: Roboto Mono
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

features:
  - search.suggest
  - search.highlight
  - navigation.footer
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.code.select

plugins:
  - obsidian-interactive-graph
  - search
  - callouts
  - embed_file
  - obsidian-bridge
  # - obsidian-support
  - glightbox
  - blogging:
      dirs:
        - post
      template: overrides/custom-blog.html
      features:
        tags:
          index_page: tags.md
          insert: bottom
      time_format: '%d-%m-%Y'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - md_in_html
  - def_list
  - sane_lists
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/obsidian_tags.css
  - assets/stylesheets/interactive_graph.css
  - assets/stylesheets/embed_link.css

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/interactive_graph.js
  - assets/javascripts/obsidian_tags.js

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@nguyenhaihabk
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/hahtd3
    - icon: fontawesome/solid/bookmark
      link: https://substack.com/@nguyenhaiha
    - icon: fontawesome/solid/globe
      link: https://www.khoahocobsidian.com

copyright: Copyright &copy; 2024 haihanguyen

nav:
  - Trang chủ: index.md
  - Giới thiệu: about.md
  - Obsidian cơ bản:
      - Bài 1:
          title: "Hướng dẫn xem bài và trả bài trên website và Facebook Group"
          url: "https://www.youtube.com/watch?v=ULiLb4jYfgk"
      - Bài 2:
          title: "Hướng dẫn cài đặt Obsidian trên Windows or Mac"
          url: "https://www.facebook.com/groups/219067851029823/posts/220012227602052/"
      - Bài 3:
          title: "Cách chia sẻ file nhanh với Obsidian_quickShare Plugin"
          url: "https://www.youtube.com/watch?v=OG3ZutPNDb8&fbclid=IwAR2IDYg-EVx79Cc6QTPT0kgb3NQLztHdf_jVR6k_wXKvA6YmELjnnuLOIwk"
      - Bài 4:
          title: "Lấy file được chia sẻ hoặc lưu website về"
          url: "https://www.youtube.com/watch?v=OG3ZutPNDb8"
      - Bài 5:
          title: "Link Download Extension"
          url: "https://chrome.google.com/webstore/detail/markdownload-markdown-web/pcmpcfapbekmbjjkdalcgopdkipoggdi?fbclid=IwAR0NBRCwT2aJmHdVebu6AYvDEfLng_Scv3Fj3siKDdJwj9AvtM1IH6eKFn4"
      - Bài 6:
          title: "Hướng dẫn làm việc giữa nhiều máy tính"
          url: "https://www.facebook.com/groups/219067851029823/posts/220015034268438/"
      - Bài 7:
          title: "Bắt đầu với những khái niệm ban đầu"
          url: "https://www.facebook.com/groups/219067851029823/posts/221994450737163/"
      - Bài 8:
          title: "Cách tạo một note theo ngày"
          url: "https://www.facebook.com/groups/219067851029823/posts/224577793812162/"
      - Bài 9:
          title: "Hướng dẫn dùng Canvas"
          url: "https://www.facebook.com/groups/219067851029823/posts/227692430167365/"
      - Bài 10:
          title: "Vẽ Mindmap trong Canvas (Cách 1)"
          url: "https://www.facebook.com/groups/219067851029823/posts/235964019340206/"
      - Bài 11:
          title: "Vẽ Mindmap trong Canvas (Cách 2)"
          url: "https://www.facebook.com/groups/219067851029823/posts/247747488161859/"
      - Bài 12:
          title: "Bài Tags và làm việc với tags"
          url: "https://www.facebook.com/groups/219067851029823/posts/227941730142435/"
      - Bài 13:
          title: "Các phương pháp tìm kiếm file"
          url: "https://www.facebook.com/groups/219067851029823/posts/232932222976719/"
      - Bài 14:
          title: "Hướng dẫn tìm kiếm file cơ bản"
          url: "https://www.facebook.com/groups/219067851029823/posts/227826946820580/"
      - Bài 15:
          title: "Hướng dẫn tìm kiếm file nâng cao"
          url: "https://www.facebook.com/groups/219067851029823/posts/227804093489532/"
      - Bài 16:
          title: "Chữa bài - Một số khó khăn"
          url: "https://www.facebook.com/groups/219067851029823/posts/231620186441256/"
      - Bài 17:
          title: "Một số Tip"
          url: "https://www.facebook.com/groups/219067851029823/posts/239179162352025/"
      - Bài 18:
          title: "Làm việc với các Workspace"
          url: "https://www.facebook.com/groups/219067851029823/posts/359309507005656/"

  - Danh sách bài học nâng cao:
      - Bài 19:
          title: "Hướng dẫn xem mindmap của notes"
          url: "https://www.facebook.com/groups/219067851029823/posts/250546011215340/"
      - Bài 20:
          title: "Hướng dẫn dùng plugin Quickadd-nâng cao của template"
          url: "https://www.facebook.com/groups/219067851029823/posts/251081967828411/"
      - Bài 21:
          title: "Hướng dẫn sử dụng Plugin giữa nhiều vault"
          url: "https://www.facebook.com/groups/219067851029823/posts/223744593895482/"
      - Bài 22:
          title: "Hướng dẫn xử lý ảnh chèn vào notes"
          url: "https://www.facebook.com/groups/219067851029823
